apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  labels:
    app: elastic-stack
    component: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: elastic-cluster

    node.data: true
    node.ingest: true
    node.master: true

    node.name: ${hostname}

    network.host: 0.0.0.0

    discovery:
      zen:
        ping.unicast.hosts: elasticsearch-discovery
        minimum_master_nodes: 2