apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elastic-stack
    component: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elastic-stack
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    app: elastic-stack
    component: elasticsearch
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elastic-stack
    component: elasticsearch
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
